version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sample
    ports:
      - 27017:27017
    volumes:
      - ./backend/mongodb_data:/data/db
      - ./backend/configdb:/data/configdb
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
    depends_on:
      - mongo
